routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/main', function () {
//     return view('layouts.main');
// });

// Route::get('/products/gallery', 'ProductController@gallery');
// Route::get('/brands/gallery', 'BrandController@gallery');

// Route::get('/users/editpassword', function () {
//     return view('users.editpassword');
// });

// Route::get('/products/gallery', 'ProductController@gallery');
// Route::get('/brands/gallery', 'BrandController@gallery');

// Route::resource('products', 'ProductController');
// Route::resource('suppliers', 'SupplierController');
// Route::resource('brands', 'BrandController');

Route::middleware('auth')->group(function () {
    Route::get('/products/gallery', 'ProductController@gallery')->name('products.gallery');
    Route::resource('products', 'ProductController');
    Route::resource('suppliers', 'SupplierController');
    Route::get('/brands/gallery', 'BrandController@gallery')->name('brands.gallery');
    Route::resource('brands', 'BrandController');
    Route::get('/','UserController@dashboard');
    // Route::get('/dashboard', 'UserController@dashboard');
    Route::get('/gallery', 'ProductController@galleryindex')->name('gallery.index');


});

Route::middleware(['auth', 'can:manage-users'])->group(function () {
    Route::get('/users/{user}/editpassword', 'UserController@editpassword')->name('users.editpassword');
    Route::put('/users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
    Route::resource('users', 'UserController');
});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $fillable = [
        'name',
        'logo',
        'description',
        'est',
        'supplier_id',
        'product_id',
    ];

    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public static function boot()
	{
		parent::boot();

		static::deleting(function ($brand) { // before delete() method call this
			$brand->products()->delete();
			// do the rest of the cleanup...
		});
	}
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\Supplier;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    public function index()
    {
        $brands = Brand::oldest()->paginate(5);

        return view('brands.index', compact('brands'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $suppliers = Supplier::all();
        return view('brands.create', compact('suppliers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:100',
            'logo' => 'mimes:jpeg,jpg,png|required|image|max:600',
            'description' => 'required|max:200',
            'est' => 'required|numeric',
            'supplier_id' => 'required|numeric',
            // 'product_id' => 'required|numeric',
        ]);

        $logo = $request->file('logo');
        $imagedata = file_get_contents($logo);
        $base64 = base64_encode($imagedata);

        $brand = new Brand();
        $brand->name = $request->name;
        $brand->logo = $base64;
        $brand->description = $request->description;
        $brand->est = $request->est;
        $brand->supplier_id = $request->supplier_id;
        $brand->user_id = $request->user()->id;
        // $brand->product_id = $request->product_id;

        $brand->save();

        // Brand::create($request->all());

        return redirect()->route('brands.index')
            ->with('success', 'Brand created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        return view('brands.show', compact('brand'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('update-brand', $brand);

        $suppliers = Supplier::all();
        return view('brands.edit', compact('brand', 'suppliers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('update-brand', $brand);

        $request->validate([
            'name' => 'required|max:100',
            'logo' => 'mimes:jpeg,jpg,png|image|max:600',
            'description' => 'required|max:200',
            'est' => 'required|numeric',
            'supplier_id' => 'required|numeric',
            // 'product_id' => 'required|numeric',
        ]);

        if ($request->file('logo') != null) {
            $logo = $request->file('logo');
            $imagedata = file_get_contents($logo);
            $base64 = base64_encode($imagedata);

            $brand->name = $request->name;
            $brand->logo = $base64;
            $brand->description = $request->description;
            $brand->est = $request->est;
            $brand->supplier_id = $request->supplier_id;


            $brand->update();
        } else {
            $brand->update($request->all());
        }



        // $brand->product_id = $request->product_id;



        return redirect()->route('brands.index')
            ->with('success', 'Brand updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brand $brand)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('delete-brand', $brand);

        $brand->delete();

        return redirect()->route('brands.index')
            ->with('success', 'Brand deleted successfully');
    }
    public function gallery()
    {
        $brands = Brand::oldest()->paginate();

        return view('brands.gallery', compact('brands'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
    
}

resources/views/brands/create.blade.php
@extends('layouts.main')

@section('content')
<head>
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(150)
                    .height(200);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<style>
	.btn.btn-back {
		margin-top: 20px;
		margin-bottom: 15px;
		margin-left: 20px;
	}

	.header-text {
		margin-top: 10px;
		margin-left: 20px;
		margin-bottom: 5px;
		font-size: 30px;
		font-family: 'Raleway', sans-serif;
		font-weight: bold;
	}

	.row.input-pic {
		margin-left: 8px;
		margin-bottom: 30px
	}

	.btn-add {
		margin-left: 13px;
		margin-bottom: 40px;
	}

	hr {
        margin-bottom: 20px;
    }

    .req-text {
        margin-bottom: 30px;
    }

</style>
</head>

<div class="container">
    <div class="row">
		<a class="btn btn-back btn-primary" href="{{ route('brands.index') }}"> Back</a>
	</div>

	<div class="row">
		<h3 class="header-text"> Add New Brand </h3>
	</div>

	<hr>

    <div class="req-text">
        <text>Photo size of 500x500 is recommended and file size of less than 600kb is required.</text>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('brands.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

        <div class="row input-pic">
            <input type='file' onchange="readURL(this);" name="logo" accept="image/png, image/jpeg, image/jpg" required focus/>
            <img id="blah" src="#" alt="your logo" />
			<span class="text-danger">{{ $errors->first('logo') }}</span>
        </div>

        <hr>

        <div class="row">
            <div class="form-group col-md-6">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name" required focus>
				<span class="text-danger">{{ $errors->first('name') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description" required focus></textarea>
				<span class="text-danger">{{ $errors->first('description') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Estalished Since:</strong>
                <input type="number" name="est" class="form-control" min="1000" max="2020" step="1" value="2020" placeholder="Year of Establish" required focus>
				<span class="text-danger">{{ $errors->first('est') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Supplier:</strong>
                <select class="form-control" name="supplier_id" required focus>
                    <option value="" disabled selected>Please select supplier</option>
                    @foreach($suppliers as $supplier)
                        <option value="{{$supplier->id}}">{{ $supplier->name }} </option>
                    @endforeach
                </select>
				<span class="text-danger">{{ $errors->first('supplier_id') }}</span>
            </div>
            
            <button type="submit" class="btn btn-add btn-success col-sm-2">Add</button>
        </div>
    </form>
</div>

@endsection

resources/views/brands/edit.blade.php
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(200)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
    <style>
        .btn.btn-back {
            margin-top: 20px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 10px;
            margin-left: 20px;
            margin-bottom: 5px;
            font-size: 30px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .row.input-pic {
            margin-left: 8px;
            margin-bottom: 30px
        }

        .btn-update {
            margin-left: 13px;
            margin-bottom: 40px;
        }

        hr {
            margin-bottom: 20px;
        }
    </style>
</head>

<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('brands.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Edit Brand </h3>
    </div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('brands.update',$brand->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row input-pic">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <!-- <label for="img">Select image:</label>
                    <input type="file" id="img" name="image" accept="image/*"> -->
                    <input type='file' onchange="readURL(this);" name="logo" accept="image/png, image/jpeg" />
                    <img id="blah" src="data:image/jpeg;base64,{{$brand->logo}}" width="200" height="200" />
                    <span class="text-danger">{{ $errors->first('logo') }}</span>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="form-group col-md-12">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $brand->name }}" class="form-control" placeholder="Name">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description">{{ $brand->description }}</textarea>
                <span class="text-danger">{{ $errors->first('description') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Established Since:</strong>
                <input type="number" name="est" class="form-control" min="1900" max="2020" step="1" value="{{ $brand->est }}" placeholder="Year of Establish" required focus>
                <span class="text-danger">{{ $errors->first('est') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Supplier:</strong>
                <select class="form-control" name="supplier_id" required focus>
                    <option value="{{ $brand->supplier_id }}" selected="{{ $brand->supplier_id }}">{{ $brand->supplier->name }} - {{$brand->supplier_id}}</option>
                    @foreach($suppliers as $supplier)
                    @if($supplier->id == $brand->supplier_id)
                    @continue;
                    @endif
                    <option value="{{$supplier->id}}">{{ $supplier->name }} - {{ $supplier->id }}</option>
                    @endforeach
                </select>
                <span class="text-danger">{{ $errors->first('supplier_id') }}</span>
            </div>

            <!-- <div class="form-group col-md-12">
                    <strong>Product ID:</strong>
                    <input type="number" name="product_id" value="{{ $brand->product_id }}" class="form-control" placeholder="Product ID">
                </div> -->

            <button type="submit" class="btn btn-update btn-success col-sm-2">Update</button>
        </div>
    </form>
</div>
@endsection

resources/views/brands/gallery.blade.php
@extends('layouts.main')


@section('content')

<head>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {

            $('.image-popup-vertical-fit').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                mainClass: 'mfp-img-mobile',
                image: {
                    verticalFit: true
                }

            });

            $('.image-popup-fit-width').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                image: {
                    verticalFit: false
                }
            });

            $('.image-popup-no-margins').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                closeBtnInside: false,
                fixedContentPos: true,
                mainClass: 'mfp-no-margins mfp-with-zoom', // class to remove default margin from left and right side
                image: {
                    verticalFit: true
                },
                zoom: {
                    enabled: true,
                    duration: 300 // don't foget to change the duration also in CSS
                }
            });

        });
    </script>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style>
        .row-pic {
            margin-left: 100px;
        }

        .row.pic {
            margin-bottom: 10px;
        }

        .text {
            text-align: center;
        }

        .picturecontainer {
            display: block;
            margin: 20px;
        }

        .header-text {
            margin-top: 20px;
            margin-left: 35px;
            font-size: 25px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .image:hover {
            filter: opacity(60%);
        }

        /* padding-bottom and top for image */
        .mfp-no-margins img.mfp-img {
            padding: 0;
            height: 500px;
            width: 500px;
        }

        /* position of shadow behind the image */
        .mfp-no-margins .mfp-figure:after {
            top: 0;
            bottom: 0;
        }

        /* padding for main container */
        .mfp-no-margins .mfp-container {
            padding: 0;
        }


        .mfp-with-zoom .mfp-container,
        .mfp-with-zoom.mfp-bg {
            opacity: 0;
            -webkit-backface-visibility: hidden;
            -webkit-transition: all 0.3s ease-out;
            -moz-transition: all 0.3s ease-out;
            -o-transition: all 0.3s ease-out;
            transition: all 0.3s ease-out;
        }

        .mfp-with-zoom.mfp-ready .mfp-container {
            opacity: 1;
        }

        .mfp-with-zoom.mfp-ready.mfp-bg {
            opacity: 0.8;
        }

        .mfp-with-zoom.mfp-removing .mfp-container,
        .mfp-with-zoom.mfp-removing.mfp-bg {
            opacity: 0;
        }
    </style>
</head>
<div class="row">
    <h3 class="header-text"> Brands Photo Gallery </h3>
</div>
<div class="row row-pic">
    @foreach($brands as $brand)
    <div class="picturecontainer">
        <a class="image-popup-no-margins" href="data:image/jpeg;base64,{{$brand->logo}}"><img src="data:image/jpeg;base64,{{$brand->logo}}" width="300" height="300"></a>
        <br>
        <a href="{{ route('brands.show',$brand->id) }} ">
            <center><strong>{{$brand->name}}</strong></center>
        </a>
    </div>
    @endforeach
    <!-- @foreach($brands as $brand)
                <div class="picturecontainer">
                      <div class="row pic">
                        <a href="{{ route('brands.show',$brand->id) }} "> <img class='image' id="blah" src="data:image/jpeg;base64,{{$brand->logo}}" width="300" height="300" /></a>
                      </div>
                </div>
            @endforeach -->
</div>
</div>

@endsection

resources/views/brands/index.blade.php
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

    <style>
        .btn.btn-add {
            margin-top: 10px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .btn.btn-action {
            margin-top: 5px;
            margin-bottom: 5px;
            margin-left: 20px;
            margin-right: 10px;
        }

        .header-text {
            margin-top: 20px;
            margin-left: 35px;
            font-size: 25px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .table {
            margin-left: 20px;
            margin-right: 0;
        }

        th {
            font-family: 'Raleway', sans-serif;
        }

        td {
            word-wrap: break-word;
        }

        .alert {
            margin-left: 20px;
            max-height: 50px;
        }
    </style>
</head>

<div class="row">
    <h3 class="header-text"> Manage Brands </h3>
</div>

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right">
            <a class="btn btn-add btn-success" href="{{ route('brands.create') }}"> + Add New Brand</a>
            <a class="btn btn-add btn-success" href="{{ route('brands.gallery') }}">Brands Photo Gallery</a>

        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Logo</th>
            <th>Description</th>
            <th>Established Since</th>
            <th>Supplier</th>
            <th>Item(s)</th>
            <th>Action</th>
        </tr>
    </thead>

    </tbody>
    @foreach ($brands as $brand)

    <tr>
        <td width="1%">{{ ++$i }}</td>
        <td width="15%">{{ $brand->name }}</td>
        <td width="10%"><img src="data:image/jpeg;base64,{{$brand->logo}}" width="150" height="150" /></td>
        <td width="30%">{{ $brand->description }}</td>
        <td width="10%">{{ $brand->est }}</td>
        <td width="15%"><a href={{ route('suppliers.show',$brand->supplier->id) }}>{{ $brand->supplier->name }}</a></td>
        <td width="15%">@foreach ( $brand->products as $product) 
            <li>
                <a href={{ route('products.show',$product->id) }}>{{$product->name}}</a> 
            </li>
            @endforeach
        </td>
        <td width="10%">
            <form action="{{ route('brands.destroy',$brand->id) }}" method="POST">
                <div class="row">
                    <a class="btn btn-action btn-primary" href="{{ route('brands.show',$brand->id) }}">Show</a>
                </div>
                @if (Auth::user()->can('manage-inventory')|| Auth::user()->can('update-brand', $brand))
                <div class="row">
                    <a class="btn btn-action btn-warning" href="{{ route('brands.edit',$brand->id) }}">Edit</a>
                </div>
                @endif
                @if (Auth::user()->can('manage-inventory')|| Auth::user()->can('delete-brand', $brand))
                <div class="row">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-action btn-danger" onclick="return confirm('Are you sure? All associated products with this brand will be removed.')">Delete</button>
                </div>
                @endif
            </form>
        </td>
    </tr>
    @endforeach
    </tbody>
</table>

{!! $brands->links() !!}

@endsection

resources/views/brands/show.blade.php
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style>
        .btn.btn-back {
            margin-top: 20px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 10px;
            margin-left: 20px;
            margin-bottom: 5px;
            font-size: 30px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .row.pic {
            margin-left: 8px;
            margin-bottom: 30px
        }

        .btn-add {
            margin-left: 13px;
            margin-bottom: 40px;
        }

        hr {
            margin-bottom: 20px;
        }

        label {
            display: inline-block;
            width: 200px;
            text-align: left;
            font-size: 17px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .desc {
            padding-left: 124px;
        }

        .container {
            margin-bottom: 40px;
        }
    </style>
    <div class="container">
        <div class="row">
            <a class="btn btn-back btn-primary" href="{{ route('brands.index') }}"> Back</a>
        </div>

        <div class="row">
            <h3 class="header-text"> Show Brand </h3>
        </div>

        <hr>

        <div class="row pic">
            <img id="blah" src="data:image/jpeg;base64,{{$brand->logo}}" width="300" height="300" />
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <label>Name</label>
                {{ $brand->name }}
            </div>
        </div>

        <div class="row">
            <div class="form-group col-1">
                <label>Description</label>
            </div>
            <div class="col-md desc">
                {{ $brand->description }}
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <label>Established Since</label>
                {{ $brand->est }}
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <label>Supplier</label>
                <a href={{route('suppliers.show',$brand->supplier->id)}}>{{ $brand->supplier->name }}</a>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <label>Item(s)</label>
                @foreach ( $brand->products as $product) <li><a href={{ route('products.show',$product->id) }}>{{$product->name}}</a></li> @endforeach
            </div>
        </div>

    </div>
    </div>
    @endsection