routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/main', function () {
//     return view('layouts.main');
// });

// Route::get('/products/gallery', 'ProductController@gallery');
// Route::get('/brands/gallery', 'BrandController@gallery');

// Route::get('/users/editpassword', function () {
//     return view('users.editpassword');
// });

// Route::get('/products/gallery', 'ProductController@gallery');
// Route::get('/brands/gallery', 'BrandController@gallery');

// Route::resource('products', 'ProductController');
// Route::resource('suppliers', 'SupplierController');
// Route::resource('brands', 'BrandController');

Route::middleware('auth')->group(function () {
    Route::get('/products/gallery', 'ProductController@gallery')->name('products.gallery');
    Route::resource('products', 'ProductController');
    Route::resource('suppliers', 'SupplierController');
    Route::get('/brands/gallery', 'BrandController@gallery')->name('brands.gallery');
    Route::resource('brands', 'BrandController');
    Route::get('/','UserController@dashboard');
    // Route::get('/dashboard', 'UserController@dashboard');
    Route::get('/gallery', 'ProductController@galleryindex')->name('gallery.index');


});

Route::middleware(['auth', 'can:manage-users'])->group(function () {
    Route::get('/users/{user}/editpassword', 'UserController@editpassword')->name('users.editpassword');
    Route::put('/users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
    Route::resource('users', 'UserController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
  protected $fillable = [
    'name',
    'brand_id',
    'description',
    'category',
    'image',
    'quantity',
    'supplier_id',
  ];

  public function brand()
  {
    return $this->belongsTo(Brand::class);
  }

  public function user()
  {
    return $this->belongsTo(User::class);
  }

  // public function supplier()
  // {
  //   return $this->belongsTo(Supplier::class);
  // }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

use App\Product;
use App\Brand;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::oldest()->paginate(5);

        return view('products.index', compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands = Brand::all();

        return view('products.create', compact('brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:100',
            'brand_id' => 'required|numeric',
            'description' => 'required|max:200',
            'category' => 'required',
            'image' => 'mimes:jpeg,jpg,png|required|image|max:600',
            // 'supplier_id' => 'required|numeric',
            'quantity' => 'required|numeric',
        ]);

        $image = $request->file('image');
        $imagedata = file_get_contents($image);
        $base64 = base64_encode($imagedata);

        $product = new Product();
        $product->name = $request->name;
        $product->description = $request->description;
        $product->brand_id = $request->brand_id;
        $product->category = $request->category;
        $product->image = $base64;
        // $product->supplier_id = $request->supplier_id;
        $product->user_id = $request->user()->id;
        $product->quantity = $request->quantity;

        $product->save();

        // Product::create($request->all());

        return redirect()->route('products.index')
            ->with('success', 'Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('update-product', $product);

        $brands = Brand::all();
        return view('products.edit', compact('product', 'brands'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('update-product', $product);

        $request->validate([
            'name' => 'required|max:100',
            'brand_id' => 'required|numeric',
            'description' => 'required|max:200',
            'category' => 'required',
            'image' => 'mimes:jpeg,jpg,png|image|max:600',
            // 'supplier_id' => 'required|numeric',
            'quantity' => 'required|numeric',
        ]);

        if ($request->file('image') != null) {

            $image = $request->file('image');
            $imagedata = file_get_contents($image);
            $base64 = base64_encode($imagedata);

            $product->name = $request->name;
            $product->description = $request->description;
            $product->category = $request->category;
            $product->brand_id = $request->brand_id;
            $product->image = $base64;
            // $product->supplier_id = $request->supplier_id;
            $product->quantity = $request->quantity;

            $product->update();
        } else {
            $product->update($request->all());
        }


        return redirect()->route('products.index')
            ->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('delete-product', $product);

        $product->delete();

        return redirect()->route('products.index')
            ->with('success', 'Product deleted successfully');
    }

    public function gallery()
    {
        $products = Product::oldest()->paginate();

        return view('products.gallery', compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
    public function galleryindex()
    {
        $products = Product::oldest()->paginate();
        $brands = Brand::oldest()->paginate();


        return view('gallery.index', compact('products','brands'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
}

resources/views/products/create.blade.php
<?php
use App\Common;
?>
@extends('layouts.main')

@section('content')
<head>
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .width(200)
                    .height(200);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<style>
	.btn.btn-back {
		margin-top: 20px;
		margin-bottom: 15px;
		margin-left: 20px;
	}

	.header-text {
		margin-top: 10px;
		margin-left: 20px;
		margin-bottom: 5px;
		font-size: 30px;
		font-family: 'Raleway', sans-serif;
		font-weight: bold;
	}

	.row.input-pic {
		margin-left: 8px;
		margin-bottom: 30px
	}

	.btn-add {
		margin-left: 13px;
		margin-bottom: 40px;
	}

	hr {
        margin-bottom: 20px;
    }

	.req-text {
        margin-bottom: 30px;
    }

</style>
</head>

<div class="container">
	<div class="row">
		<a class="btn btn-back btn-primary" href="{{ route('products.index') }}"> Back</a>
	</div>

	<div class="row">
		<h3 class="header-text"> Add New Product </h3>
	</div>

	<hr>

	<div class="req-text">
        <text>Photo size of 500x500 is recommended and file size of less than 600kb is required.</text>
    </div>

	@if ($errors->any())
	<div class="alert alert-danger">
			<strong>Whoops!</strong> There were some problems with your input.<br><br>
			<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
			</ul>
	</div>
	@endif

	<form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
	@csrf

		<div class="row input-pic">
			<input type='file' onchange="readURL(this);" name="image" accept="image/png, image/jpeg" required focus/>
			<img id="blah" src="#" alt="your image" width="200" height="200"/>
			<span class="text-danger">{{ $errors->first('image') }}</span>
		</div>

		<hr>

		<div class="row">
			<div class="form-group col-md-6">
				<strong>Name:</strong>
				<input type="text" name="name" class="form-control" placeholder="Name" required focus>
				<span class="text-danger">{{ $errors->first('name') }}</span>
			</div>

			<div class="form-group col-md-12">
				<strong>Brand:</strong>
				<select class="form-control" name="brand_id" required focus>
                    <option value="" disabled selected>Please select Brand</option>
                    @foreach($brands as $brand)
                        <option value="{{$brand->id}}">{{ $brand->name }}</option>
                    @endforeach
                </select>
				<span class="text-danger">{{ $errors->first('brand_id') }}</span>
			</div>

			<!-- <div class="form-group col-md-12">
				<strong>Supplier:</strong>
				<input type="number" name="supplier_id" class="form-control" placeholder="Supplier">
			</div> -->

			<div class="form-group col-md-12">
				<strong>Description:</strong>
				<textarea class="form-control" style="height:150px" name="description" placeholder="Description" required focus></textarea>
				<span class="text-danger">{{ $errors->first('description') }}</span>
			</div>

			<div class="form-group col-md-12">
				<strong>Category:</strong>
				<select class="form-control" name="category" required focus>

                    <option value="" disabled selected>Please select category</option>
                    @foreach(Common::$categories as $category)
                        <option value="{{$category}}">{{ $category }}</option>
                    @endforeach
                </select>
				<span class="text-danger">{{ $errors->first('category') }}</span>
			</div>

			<div class="form-group col-md-12">
				<strong>Quantity:</strong>
				<input type="number" name="quantity" class="form-control" placeholder="Quantity" required focus>
				<span class="text-danger">{{ $errors->first('quantity') }}</span>
			</div>

			<button type="submit" class="btn btn-add btn-success col-sm-2">Add</button>
		</div>
	</form>
</div>

@endsection

resources/views/products/edit.blade.php
<?php

use App\Common;
?>
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $('#blah')
                        .attr('src', e.target.result)
                        .width(200)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
    <style>
        .btn.btn-back {
            margin-top: 20px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 10px;
            margin-left: 20px;
            margin-bottom: 5px;
            font-size: 30px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .row.input-pic {
            margin-left: 8px;
            margin-bottom: 30px
        }

        .btn-update {
            margin-left: 13px;
            margin-bottom: 40px;
        }

        hr {
            margin-bottom: 20px;
        }
    </style>
</head>

<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('products.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Edit Product </h3>
    </div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row input-pic">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <!-- <label for="img">Select image:</label>
                    <input type="file" id="img" name="image" accept="image/*"> -->
                    <input type='file' onchange="readURL(this);" name="image" accept="image/png, image/jpeg" />
                    <img id="blah" src="data:image/jpeg;base64,{{$product->image}}" width="200" height="200" />
                    <span class="text-danger">{{ $errors->first('image') }}</span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Name">
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Brand:</strong>
                <select class="form-control" name="brand_id" required focus>
                    <option value="{{$product->brand_id}}" selected="{{$product->brand_id}}">{{ $product->brand->name }} - {{$product->brand_id}}</option>
                    @foreach($brands as $brand)
                    @if($brand->id == $product->brand_id)
                    @continue;
                    @endif
                    <option value="{{$brand -> id}}">{{ $brand->name }} - {{ $brand->id }}</option>
                    @endforeach
                </select>
                <span class="text-danger">{{ $errors->first('brand_id') }}</span>
            </div>

            <!-- <div class="form-group col-md-12">
                <strong>Supplier ID:</strong>
                <input type="number" name="supplier_id" value="{{ $product->supplier_id }}" class="form-control" placeholder="Supplier ID">
            </div> -->

            <div class="form-group col-md-12">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description">{{ $product->description }}</textarea>
                <span class="text-danger">{{ $errors->first('description') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Category:</strong>
                <select class="form-control" name="category" required focus>
                    <option value="{{$product->category}}" selected="{{$product->category}}">{{$product->category}}</option>
                    @foreach(Common::$categories as $category)
                    @if($category == $product->category)
                    @continue;
                    @endif
                    <option value="{{$category}}">{{ $category }}</option>
                    @endforeach
                </select>
                <span class="text-danger">{{ $errors->first('category') }}</span>
            </div>

            <div class="form-group col-md-12">
                <strong>Quantity:</strong>
                <input type="number" name="quantity" value="{{ $product->quantity }}" class="form-control" placeholder="quantity">
                <span class="text-danger">{{ $errors->first('quantity') }}</span>
            </div>

            <button type="submit" class="btn btn-update btn-success col-sm-2">Update</button>
        </div>
    </form>
</div>
@endsection

resources/views/products/gallery.blade.php
@extends('layouts.main')


@section('content')

<head>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

    Optional theme
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" /> -->

    <!-- Latest compiled and minified JavaScript
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {

            $('.image-popup-vertical-fit').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                mainClass: 'mfp-img-mobile',
                image: {
                    verticalFit: true
                }

            });

            $('.image-popup-fit-width').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                image: {
                    verticalFit: false
                }
            });

            $('.image-popup-no-margins').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                closeBtnInside: false,
                fixedContentPos: true,
                mainClass: 'mfp-no-margins mfp-with-zoom', // class to remove default margin from left and right side
                image: {
                    verticalFit: true
                },
                zoom: {
                    enabled: true,
                    duration: 300 // don't foget to change the duration also in CSS
                }
            });

        });
    </script>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style>
        .row-pic {
            margin-left: 100px;
        }

        .row.pic {
            margin-bottom: 10px;
        }

        .text {
            text-align: center;
        }

        .picturecontainer {
            display: block;
            margin: 20px;
        }

        center {
            word-wrap: break-word;
        }

        .header-text {
            margin-top: 20px;
            margin-left: 35px;
            font-size: 25px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .image:hover {
            filter: opacity(60%);
        }

        /* padding-bottom and top for image */
        .mfp-no-margins img.mfp-img {
            padding: 0;
            height: 500px;
            width: 500px;
        }

        /* position of shadow behind the image */
        .mfp-no-margins .mfp-figure:after {
            top: 0;
            bottom: 0;
        }

        /* padding for main container */
        .mfp-no-margins .mfp-container {
            padding: 0;
        }


        .mfp-with-zoom .mfp-container,
        .mfp-with-zoom.mfp-bg {
            opacity: 0;
            -webkit-backface-visibility: hidden;
            -webkit-transition: all 0.3s ease-out;
            -moz-transition: all 0.3s ease-out;
            -o-transition: all 0.3s ease-out;
            transition: all 0.3s ease-out;
        }

        .mfp-with-zoom.mfp-ready .mfp-container {
            opacity: 1;
        }

        .mfp-with-zoom.mfp-ready.mfp-bg {
            opacity: 0.8;
        }

        .mfp-with-zoom.mfp-removing .mfp-container,
        .mfp-with-zoom.mfp-removing.mfp-bg {
            opacity: 0;
        }
    </style>
</head>
<div class="row">
    <h3 class="header-text"> Products Photo Gallery </h3>
</div>
<div class="row row-pic">
    @foreach($products as $product)
    <div class="picturecontainer">
        <a class="image-popup-no-margins" href="data:image/jpeg;base64,{{$product->image}}"><img src="data:image/jpeg;base64,{{$product->image}}"  width="300" height="300"></a>
        <br>
        <a href="{{ route('products.show',$product->id) }} ">
            <center><strong>{{$product->name}}</strong></center>
        </a>
    </div>
    @endforeach
    <!-- @foreach($products as $product)
    <div class="picturecontainer">
        <div class="row pic">
            <a href="{{ route('products.show',$product->id) }} "> <img class='image' id="blah" src="data:image/jpeg;base64,{{$product->image}}" width="300" height="300" /></a>
    </div>
</div>
@endforeach -->
</div>
</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

    <style>
        .btn.btn-add {
            margin-top: 10px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .btn.btn-action {
            margin-top: 5px;
            margin-bottom: 5px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 20px;
            margin-left: 35px;
            font-size: 25px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .table {
            margin-left: 20px;
            margin-right: 0;
        }

        th {
            font-family: 'Raleway', sans-serif;
        }

        td {
            word-wrap: break-word;
        }

        .alert {
            margin-left: 20px;
            max-height: 50px;
        }
    </style>
</head>

<div class="row">
    <h3 class="header-text"> Manage Products </h3>
</div>

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right">
            <a class="btn btn-add btn-success" href="{{ route('products.create') }}"> + Add New Product</a>
              <a class="btn btn-add btn-success" href="{{ route('products.gallery') }}">Products Photo Gallery</a>
        </div>
    </div>

</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <thead>
        <tr>
            <th width="5px">#</th>
            <th>Name</th>
            <th>Brand</th>
            <th>Supplier</th>
            <th>Description</th>
            <th>Category</th>
            <th>Quantity</th>
            <th>Image</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        @foreach ($products as $product)
        <tr>
            <td width="1%">{{ ++$i }}</td>
            <td width="8%">{{ $product->name }}</td>
            <td width="8%"><a href={{ route('brands.show',$product->brand->id) }}>{{ $product->brand -> name }}</a></td>
            <td width="8%"><a href={{ route('suppliers.show',$product->brand->supplier->id) }}>{{$product->brand -> supplier-> name}}</a></td>
            <td width="12%">{{ $product->description }}</td>
            <td width="8%">{{ $product->category }}</td>
            <td width="1%">{{ $product->quantity }}</td>
            <td width="1%"><img src="data:image/jpeg;base64,{{$product->image}}" width="150px" height="150px" /></td>
            <td width="2%">
                <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                    <div class="row">
                        <a class="btn btn-action btn-primary" href="{{ route('products.show',$product->id) }}">Show</a>
                    </div>
                    @if (Auth::user()->can('manage-inventory')|| Auth::user()->can('update-product', $product))
                    <div class="row">
                        <a class="btn btn-action btn-warning" href="{{ route('products.edit',$product->id) }}">Edit</a>
                    </div>
                    @endif
                    @if (Auth::user()->can('manage-inventory')|| Auth::user()->can('delete-product', $product))
                    <div class="row">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-action btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
                    </div>
                    @endif
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

{!! $products->links() !!}

@endsection

resources/views/products/show.blade.php
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style>
        .btn.btn-back {
            margin-top: 20px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 10px;
            margin-left: 20px;
            margin-bottom: 5px;
            font-size: 30px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .row.pic {
            margin-left: 8px;
            margin-bottom: 30px
        }

        hr {
            margin-bottom: 20px;
        }

        label {
            display: inline-block;
            width: 140px;
            text-align: left;
            font-size: 17px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .desc {
            padding-left: 63px;
        }

        .container {
            margin-bottom: 40px;
        }
    </style>
</head>
<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('products.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Show Product </h3>
    </div>

    <hr>

    <div class="row pic">
        <img id="blah" src="data:image/jpeg;base64,{{$product->image}}" width="300" height="300" />
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Name</label>
            {{ $product->name }}
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Brand</label>
            <a href={{route('brands.show',$product->brand -> id)}}>{{ $product->brand -> name }}</a>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Supplier</label>
            <a href={{route('suppliers.show',$product->brand -> supplier -> id)}}>{{ $product->brand -> supplier -> name }}</a>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-1">
            <label>Description</label>
        </div>
        <div class="col-md desc">
            {{ $product->description }}
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Category</label>
            {{ $product->category }}
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Quantity</label>
            {{ $product->quantity }}
        </div>
    </div>
</div>
@endsection