routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/main', function () {
//     return view('layouts.main');
// });

// Route::get('/products/gallery', 'ProductController@gallery');
// Route::get('/brands/gallery', 'BrandController@gallery');

// Route::get('/users/editpassword', function () {
//     return view('users.editpassword');
// });

// Route::get('/products/gallery', 'ProductController@gallery');
// Route::get('/brands/gallery', 'BrandController@gallery');

// Route::resource('products', 'ProductController');
// Route::resource('suppliers', 'SupplierController');
// Route::resource('brands', 'BrandController');

Route::middleware('auth')->group(function () {
    Route::get('/products/gallery', 'ProductController@gallery')->name('products.gallery');
    Route::resource('products', 'ProductController');
    Route::resource('suppliers', 'SupplierController');
    Route::get('/brands/gallery', 'BrandController@gallery')->name('brands.gallery');
    Route::resource('brands', 'BrandController');
    Route::get('/','UserController@dashboard');
    // Route::get('/dashboard', 'UserController@dashboard');
    Route::get('/gallery', 'ProductController@galleryindex')->name('gallery.index');


});

Route::middleware(['auth', 'can:manage-users'])->group(function () {
    Route::get('/users/{user}/editpassword', 'UserController@editpassword')->name('users.editpassword');
    Route::put('/users/{user}/updatepassword', 'UserController@updatepassword')->name('users.updatepassword');
    Route::resource('users', 'UserController');
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
	protected $fillable = [
		'name',
		'company',
		'address',
		// 'brand_id',
		// 'product_id'
	];

	// public function products()
	// {
	// 	return $this->hasMany(Product::class);
	// }

	public function brands()
	{
		return $this->hasMany(Brand::class);
	}

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public static function boot()
	{
		parent::boot();

		static::deleting(function ($supplier) { // before delete() method call this
			foreach ($supplier->brands as $brand) {
				$brand->products()->delete();
			}
			$supplier->brands()->delete();

			// do the rest of the cleanup...
		});
	}
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

use App\Supplier;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    public function index()
    {
        $suppliers = Supplier::oldest()->paginate(5);


        return view('suppliers.index', compact('suppliers'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('suppliers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:100',
            'company' => 'required|max:100',
            'address' => 'required|max:200',
            // 'brand_id' => 'required|numeric',
            // 'product_id' => 'required',
        ]);
        $supplier = new Supplier();
        $supplier->fill($request->all());
        $supplier->user_id = $request->user()->id;
        $supplier->save();

        return redirect()->route('suppliers.index')
            ->with('success', 'Supplier created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        return view('suppliers.show', compact('supplier'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit(Supplier $supplier)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('update-supplier', $supplier);

        return view('suppliers.edit', compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Supplier $supplier)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('update-supplier', $supplier);

        $request->validate([
            'name' => 'required|max:100',
            'company' => 'required|max:100',
            'address' => 'required|max:200',
            // 'brand_id' => 'required|numeric',
            // 'product_id' => 'required',
        ]);


        $supplier->update($request->all());

        return redirect()->route('suppliers.index')
            ->with('success', 'Supplier updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supplier $supplier)
    {
        if (!Gate::allows('manage-inventory'))
            $this->authorize('delete-supplier', $supplier);

        $supplier->delete();

        return redirect()->route('suppliers.index')
            ->with('success', 'Supplier deleted successfully');
    }
}

resources/views/suppliers/create.blade.php
@extends('layouts.main')

@section('content')
<head>
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
<style>
	.btn.btn-back {
		margin-top: 20px;
		margin-bottom: 15px;
		margin-left: 20px;
	}
	
	.header-text {
		margin-top: 10px;
		margin-left: 20px;
		margin-bottom: 5px;
		font-size: 30px;
		font-family: 'Raleway', sans-serif;
		font-weight: bold;
	}

	.btn-add { 
		margin-left: 13px;
		margin-bottom: 40px;
	}

	hr { 
        margin-bottom: 20px;
    }

</style>
</head>

<div class="container">
    <div class="row">
		<a class="btn btn-back btn-primary" href="{{ route('suppliers.index') }}"> Back</a>
	</div>

	<div class="row">
		<h3 class="header-text"> Add New Supplier </h3>
	</div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('suppliers.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

        <div class="row">
            <div class="form-group col-md-6">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name" required focus>
				<span class="text-danger">{{ $errors->first('name') }}</span>
            </div>
        
            <div class="form-group col-md-12">
                <strong>Company:</strong>
                <input type="text" name="company" class="form-control" placeholder="Company" required focus>
				<span class="text-danger">{{ $errors->first('company') }}</span>
            </div>
        
            <div class="form-group col-md-12">
                <strong>Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Address" required focus></textarea>
				<span class="text-danger">{{ $errors->first('address') }}</span>
            </div>
        
            <!-- <div class="form-group col-md-12">
                <strong>Brand:</strong>
                <input type="number" name="brand_id" class="form-control" placeholder="Brand">
            </div> -->
        
        <button type="submit" class="btn btn-add btn-success col-sm-2">Add</button>
        </div>
    </form>
</div>

@endsection

resources/views/suppliers/edit.blade.php
@extends('layouts.main')

@section('content')
<head>
<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
</head>
<style>
	.btn.btn-back {
		margin-top: 20px;
		margin-bottom: 15px;
		margin-left: 20px;
	}
	
	.header-text {
		margin-top: 10px;
		margin-left: 20px;
		margin-bottom: 5px;
		font-size: 30px;
		font-family: 'Raleway', sans-serif;
		font-weight: bold;
	}

	.btn-update { 
		margin-left: 13px;
        margin-bottom: 40px;
	}

    hr { 
        margin-bottom: 20px;
    }

</style>

<div class="container">
    <div class="row">
		<a class="btn btn-back btn-primary" href="{{ route('suppliers.index') }}"> Back</a>
	</div>

	<div class="row">
		<h3 class="header-text"> Edit Supplier </h3>
	</div>

    <hr>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('suppliers.update',$supplier->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')

        <div class="row">       
            <div class="form-group col-md-6">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $supplier->name }}" class="form-control" placeholder="Name">
				<span class="text-danger">{{ $errors->first('name') }}</span>
            </div>
            
            <div class="form-group col-md-12">
                <strong>Company:</strong>
                <input type="text" name="company" value="{{ $supplier->company }}" class="form-control" placeholder="Company">
				<span class="text-danger">{{ $errors->first('company') }}</span>
            </div>
       
            <div class="form-group col-md-12">
                <strong>Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Address">{{ $supplier->address }}</textarea>
				<span class="text-danger">{{ $errors->first('address') }}</span>
            </div>
        
            <!-- <div class="form-group col-md-12">
                <strong>Brand ID:</strong>
                <input type="number" name="brand_id" value="{{ $supplier->brand_id }}" class="form-control" placeholder="Brand ID">
            </div> -->

            <button type="submit" class="btn btn-update btn-success col-sm-2">Update</button>
        </div>
    </form> 
</div>
@endsection

resources/views/suppliers/index.blade.php
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style>
        .btn.btn-add {
            margin-top: 10px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .btn.btn-action {
            margin-top: 5px;
            margin-bottom: 5px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 20px;
            margin-left: 35px;
            font-size: 25px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .table {
            margin-left: 20px;
            margin-right: 0;
            width: 100%;
        }

        th {
            font-family: 'Raleway', sans-serif;
        }

        td {
            word-wrap: break-word;
        }

        .alert {
            margin-left: 20px;
            max-height: 50px;
        }

        form { 
            padding-right: 20px;
        }
    </style>
</head>

<div class="row">
    <h3 class="header-text"> Manage Suppliers </h3>
</div>

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right">
            <a class="btn btn-add btn-success" href="{{ route('suppliers.create') }}"> + Add New Supplier</a>
        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th scope="col" width="1%">#</th>
        <th scope="col" width="13%">Name</th>
        <th scope="col" width="20%">Company Name</th>
        <th scope="col" width="30%">Address</th>
        <th scope="col" width="15%">Brand(s)</th>
        <th scope="col" width="30%">Item(s)</th>
        <th >Action</th>
    </tr>
    @foreach ($suppliers as $supplier)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $supplier->name }}</td>
        <td>{{ $supplier->company }}</td>
        <td>{{ $supplier->address }}</td>
        <td>@foreach ( $supplier->brands as $brand) 
            <li>
                <a href={{ route('brands.show',$brand->id) }}>{{$brand->name}} </a> 
            </li>
            @endforeach
        </td>
        <td>@foreach ( $supplier->brands as $brand) @foreach($brand->products as $product)
            <li>
                <a href={{ route('products.show',$product->id) }}>{{$product->name}}</a> 
            </li>
             @endforeach @endforeach</td>
        <td>
            <form action="{{ route('suppliers.destroy',$supplier->id) }}" method="POST">
                <div class="row">
                    <a class="btn btn-action btn-primary" href="{{ route('suppliers.show',$supplier->id) }}">Show</a>
                </div>
                @if (Auth::user()->can('manage-inventory')|| Auth::user()->can('update-supplier', $supplier))
                <div class="row">
                    <a class="btn btn-action btn-warning" href="{{ route('suppliers.edit',$supplier->id) }}">Edit</a>
                </div>
                @endif
                @if (Auth::user()->can('manage-inventory')|| Auth::user()->can('delete-supplier', $supplier))
                <div class="row">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-action btn-danger" onclick="return confirm('Are you sure? All associated brands and products with this supplier will be removed.')">Delete</button>
                </div>
                @endif
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $suppliers->links() !!}



@endsection

resources/views/suppliers/show.blade.php
@extends('layouts.main')

@section('content')

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <style>
        .btn.btn-back {
            margin-top: 20px;
            margin-bottom: 15px;
            margin-left: 20px;
        }

        .header-text {
            margin-top: 10px;
            margin-left: 20px;
            margin-bottom: 5px;
            font-size: 30px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        hr {
            margin-bottom: 20px;
        }

        label {
            display: inline-block;
            width: 140px;
            text-align: left;
            font-size: 17px;
            font-family: 'Raleway', sans-serif;
            font-weight: bold;
        }

        .desc {
            padding-left: 63px;
        }

        .container {
            margin-bottom: 40px;
        }
    </style>
</head>
<div class="container">
    <div class="row">
        <a class="btn btn-back btn-primary" href="{{ route('suppliers.index') }}"> Back</a>
    </div>

    <div class="row">
        <h3 class="header-text"> Show Supplier </h3>
    </div>

    <hr>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Name</label>
            {{ $supplier->name }}
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Company</label>
            {{ $supplier->company }}
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Address</label>
            {{ $supplier->address }}
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-12">
            <label>Brand(s) Owned:</label>
            @foreach ( $supplier->brands as $brand)<li><a href={{ route('brands.show',$brand->id) }}>{{$brand->name}}</a></li>  @endforeach
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-12">
            <label>Item(s) Owned:</label>
            @foreach ( $supplier->brands as $brand) @foreach($brand->products as $product)<li><a href={{ route('products.show',$product->id) }}>{{$product->name}}</a></li> @endforeach @endforeach
        </div>
    </div>
</div>
@endsection